#! /bin/sh
if [ -z "$JENA_HOME" ]; then
	echo '$JENA_HOME not set'
	echo 'Please do:'
	echo '   mkdir ~/jena'
	echo '   cd ~/jena'
	echo '   curl http://apache.uib.no/jena/binaries/apache-jena-3.8.0.tar.gz'
	echo '   tar xzf apache-jena-3.8.0.tar.gz'
	echo '   export JENA_HOME=$HOME/jena/apache-jena-3.8.0'
	echo "   echo  'export JENA_HOME=\$HOME/jena/apache-jena-3.8.0' >> \$HOME/.bashrc" 
	exit 1
fi

if [ $# = 0 ]; then
	echo "usage: ./query queries/file.sparql   or   ./query -q 'SELECT * WHERE { GRAPH ?g { ?a ?b ?c } }'"
	exit 1
fi

if [ "$1" = "-q" ]; then
	shift
	cat > /tmp/query.sparql <<EOF
PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd:   <http://www.w3.org/2001/XMLSchema#>
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
PREFIX jFlag: <https://model.nuthatchery.org/java/flags/>
PREFIX jType: <https://model.nuthatchery.org/java/types/>
PREFIX nh:    <https://model.nuthatchery.org/common/>
PREFIX j:     <https://model.nuthatchery.org/java/>
PREFIX jvm:   <https://model.nuthatchery.org/jvm/>
PREFIX m:     <https://model.nuthatchery.org/maven/>
PREFIX duck-0.4.2: <https://db.nuthatchery.org/org.example/duck/0.4.2/>
PREFIX duck-0.4.3: <https://db.nuthatchery.org/org.example/duck/0.4.3/>
PREFIX frog-0.3.7: <https://db.nuthatchery.org/org.example/frog/0.3.7/>
PREFIX frog-0.3.8: <https://db.nuthatchery.org/org.example/frog/0.3.8/>
PREFIX pond-0.3.0: <https://db.nuthatchery.org/org.example/pond/0.3.0/>
PREFIX pond-0.3.1: <https://db.nuthatchery.org/org.example/pond/0.3.1/>
PREFIX pond-0.3.2: <https://db.nuthatchery.org/org.example/pond/0.3.2/>
PREFIX rubberduck-0.1.2: <https://db.nuthatchery.org/org.example/rubberduck/0.1.2/>
PREFIX rubberduck-0.1.3: <https://db.nuthatchery.org/org.example/rubberduck/0.1.3/>
PREFIX A-1.0.0:  <https://db.nuthatchery.org/_/A/1.0.0/> 
PREFIX A-2.0.0:  <https://db.nuthatchery.org/_/A/2.0.0/> 
PREFIX B-1.1.1:  <https://db.nuthatchery.org/_/B/1.1.1/> 
PREFIX B-1.0.1:  <https://db.nuthatchery.org/_/B/1.0.1/> 
EOF
	for f in "$@"; do
		echo "$f" >> /tmp/query.sparql
	done
	QUERY=/tmp/query.sparql
else
	QUERY="$@"
fi

$JENA_HOME/bin/sparql --data=../examples/examples.trig --query $QUERY | sed -E -e '/^@prefix/d' -e 's;https://db.nuthatchery.org/org.example/([^/]*)/([^/]*)/;\1-\2:;g'
